### ISSUE TITLE
yarn versions issue

### ISSUE THREAD

**Issue by caduguedess** [twuni/asdf-yarn#11]
I already had yarn installed and then installed asdf and yarn 1.22.4 through `asdf install yarn latest`.
I already did `asdf global yarn 1.22.4` but when I do `yarn -v` it  still gives me the old 1.2.1 version.
`asdf list yarn` only returns me the 1.22.4 version installed through yarn.

**Comment by jvortmann** [comment]
@caduguedess can you check your $PATH if the system default / old yarn 1.2.1 is the being found?

Otherwise you can try `asdf reshim` and / or open a new terminal session.

**Comment by caduguedess** [comment]
```
carlos@cadu:~$ $PATH                                                                                                                   
-bash: /home/carlos/.asdf/shims:/home/carlos/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: No such file or directory
```

**Comment by caduguedess** [comment]
Seems like its working now.
Thanks.

**Comment by watsoncj** [comment]
I ran into this as well. Problem was the npm global installation of yarn was found.

```
$ yarn --version
1.22.4
$ npm uninstall -g yarn
$ asdf install yarn 1.22.5
$ asdf global yarn 1.22.5
$ yarn --version
1.22.5
```
