### ISSUE TITLE
Can't uninstall yarn plugin

### ISSUE THREAD

**Issue by jlurena** [twuni/asdf-yarn#17]
```
asdf plugin remove yarn
exec zsh
source ~/.zshrc
# Even opened a new tab
which yarn
  /Users/jlurena/.asdf/shims/yarn
```

**Comment by canterberry** [comment]
I'm unable to repro this locally (Linux, using zsh). In the snippet above, it looks like you're missing a dash between `plugin` and `remove`. Try `asdf plugin-remove yarn`. The change should take effect immediately (no need to re-source or login to a new session). If that still doesn't work, then maybe there's something else going on and additional context may be helpful. We'll cross that bridge if we get to it!

**Comment by jlurena** [comment]
Still persists. very weird
<img width="810" alt="2021-01-16_10-27-52" src="https://user-images.githubusercontent.com/15808412/104815888-7e1eb100-57e5-11eb-821f-bd0e0d405676.png">

**Comment by jlurena** [comment]
The following had fixed it.

1. Download Yarn plugin again
2. Use `asdf plugin-remove yarn`
3. Install any yarn version (probably not needed, but this was one of my steps)
4. Source my `.zshrc` file

**Comment by canterberry** [comment]
Ah, may just have been a shimming issue, in which case an `asdf reshim` might have been another potential fix.

**Comment by jlurena** [comment]
@canterberry i reshimed like 50 times 😄 it was something weird but I think it has more to do with `asdf` rather than the plugin

**Comment by oshanz** [comment]
same thing happned to me because yarn was installed through a different node version. after removing the other node version, issue was resolved.

`asdf list nodejs`

`asdf uninstall nodejs <version>`
