### ISSUE TITLE
Is this deprecated/unnecessary for using Yarn 2+?

### ISSUE THREAD

**Issue by dakotahp** [twuni/asdf-yarn#23]
I was reading the README and wasn't clear if using this plugin does anything if using Yarn 2+. Is it the case if Yarn can manage its own versions that I wouldn't need to use this plugin _or_ `asdf` for it? Just wanting to clarify completely since I'm confused with the version management nested within another. 

Thanks

**Comment by canterberry** [comment]
See #21 and #12.

In short: this plugin is useful/necessary to get `yarn` in the first place. Then, if you want v2+, you'd do that via yarn itself.

**Comment by dakotahp** [comment]
Thank you for those references. This helps.
