### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by obregonia1** [twuni/asdf-yarn#27]
I can't install yarn with asdf-yarn.
```
$ asdf plugin-add yarn

$ asdf install yarn latest
⛔ Missing one or more of the following dependencies: tar, gpg
```
What should I do next? Install tar and gpg with asdf?

**Comment by canterberry** [comment]
You're *probably* just missing `gpg`. You can tell for sure by running `which tar` and `which gpg`. You don't need to use asdf to install them -- use whichever install method you'd normally use for system software.

More to the point: the messaging in the CLI output isn't clear how to resolve the problem or which of the two is missing. We should update that to be more clear.

**Comment by obregonia1** [comment]
```
$ which gpg
gpg not found
```
Thanks for your answer. I didn't check gpg whether installed. And run below.

```
$ brew install gpg
$ asdf install yarn latest
$ asdf list yarn
1.22.19
```

Thank you so much:)
